#!/bin/sh
# this script is called from the postinst of all nvidia-glx{,-legacy-*} packages
set -e

. /usr/share/debconf/confmodule

CONFLICT_LIBS=""
for f in /usr/lib/libGL.so.*.*
do
	if [ -e "$f" ] || [ -L "$f" ]
	then
		CONFLICT_LIBS="$CONFLICT_LIBS $f"
	fi
done
CONFLICT_LIBS="${CONFLICT_LIBS#[ ]}"

if [ -n "$CONFLICT_LIBS" ]; then
	db_subst nvidia-common/remove-conflicting-libraries conflict-libs "$CONFLICT_LIBS"
	db_fset nvidia-common/remove-conflicting-libraries seen false
	db_input high nvidia-common/remove-conflicting-libraries
	db_go
	db_get nvidia-common/remove-conflicting-libraries
	if [ "$RET" = "true" ]; then
		backupdir=$(mktemp -d /var/tmp/nvidia-backup.XXXXXX)
		mv $CONFLICT_LIBS "$backupdir"
		echo "Moved the conflicting libraries '$CONFLICT_LIBS' to '$backupdir'."
		unset backupdir
		# fix possibly broken link
		dpkg-trigger /usr/libGL.so.1
	else
		echo "ERROR: The conflicting libraries '$CONFLICT_LIBS' still exist." >&2
		exit 1
	fi
fi


exit 0
