#!/bin/sh
# This script is called from the postinst of all libgl1-nvidia{,-legacy-*}-glx{,-ia32} packages.
set -e

. /usr/share/debconf/confmodule

# dpkg-reconfigure does not set DPKG_MAINTSCRIPT_PACKAGE (#560317)
if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]
then
	echo "ERROR: DPKG_MAINTSCRIPT_PACKAGE is not set, usually a bug in dpkg-reconfigure"
	exit 1
fi

case "$DPKG_MAINTSCRIPT_PACKAGE" in
	*-ia32*)
		libdir="/usr/lib32"
		;;
	*)
		libdir="/usr/lib"
		;;
esac

CONFLICT_LIBS=""
for f in "$libdir"/libGL.so.*.* "$libdir"/{i386,x86_64}-linux-gnu/libGL.so.*.*
do
	if [ -e "$f" ] || [ -L "$f" ]
	then
		CONFLICT_LIBS="$CONFLICT_LIBS $f"
	fi
done
CONFLICT_LIBS="${CONFLICT_LIBS#[ ]}"

if [ -n "$CONFLICT_LIBS" ]; then
	db_subst nvidia-installer-cleanup/remove-conflicting-libraries conflict-libs "$CONFLICT_LIBS"
	db_fset nvidia-installer-cleanup/remove-conflicting-libraries seen false
	db_input high nvidia-installer-cleanup/remove-conflicting-libraries
	db_go
	db_get nvidia-installer-cleanup/remove-conflicting-libraries
	if [ "$RET" = "true" ]; then
		backupdir=$(mktemp -d /var/tmp/nvidia-backup.XXXXXX)
		mv $CONFLICT_LIBS "$backupdir"
		echo "Moved the conflicting libraries '$CONFLICT_LIBS' to '$backupdir'."
		unset backupdir
		# fix possibly broken link
		dpkg-trigger /usr/libGL.so.1
		dpkg-trigger register-alternative-glx-nvidia
	else
		echo "ERROR: The conflicting libraries '$CONFLICT_LIBS' still exist." >&2
		exit 1
	fi
fi


exit 0
